<?php

// Data functions (insert, update, delete, form) for table titles

// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

function titles_insert()
{
    global $Translation;

    // mm: can member insert record?
    $arrPerm = getTablePermissions('titles');
    if (!$arrPerm[1]) {
        return false;
    }

    // ... rest of the function ...
}

function titles_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false)
{
    // ... rest of the function ...
}

function titles_update($selected_id)
{
    global $Translation;

    // ... rest of the function ...
}

function titles_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '')
{
    // ... rest of the function ...
}

// ... rest of the code ...

